version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: |
            # Build the project
            mvn -B clean verify

            # Install and Send Coverage Report to Deepsource
            curl https://deepsource.io/cli | sh
            ./bin/deepsource report --analyzer test-coverage \
                --key java \
                --value-file jacoco-report/target/site/jacoco-aggregate/jacoco.xml
      - run:
          name: Codacy Coverage
          command: |
            # CODACY_API_TOKEN is injected via Environment Variable
            export CODACY_ORGANIZATION_PROVIDER="gh"
            export CODACY_USERNAME="thedevjournal"
            export CODACY_PROJECT_NAME="code-challenges-java"

            # Install and Send Coverage Report to Codacy
            bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
                -l Java -r jacoco-report/target/site/jacoco-aggregate/jacoco.xml

workflows:
  build:
    jobs:
      - build-and-test:
          context:
            - DEEPSOURCE
            - CODACY
